sudo: required

language: java

services:
  - docker

env:
 DOCKER_COMPOSE_VERSION: 1.15.0


before_install:
- sudo /etc/init.d/mysql stop
- docker-machine ip
- cd web
- mvn clean install dockerfile:build
- docker-compose up -d

script:
- mvn -Dtest="yo.antihype.team.docker.**" test

after_script:
- docker-compose down