language: java
osx_image: xcode8.3
os: osx

install:
    - pod repo update
    - pod install

script:
    - xcodebuild -workspace Twitt.xcworkspace -scheme Twitt -destination 'platform=iOS Simulator,name=iPhone 6s,OS=11.1.1' clean build test | xcpretty
